name: Build index

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r metadata/requirements.txt

      - name: Build index
        run: python metadata/scripts/build_index.py

      - name: Commit updated index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update index [auto]"
          file_pattern: metadata/index.json
