name: Compiling and Releasing the PDFs

on:
  push:
    tags:
      - '*'

jobs:
  compile_and_release:
    container:
        image: ghcr.io/munuchapterhkn/eta-kappa-notes/texlive:latest
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dumping Version
        run: |
          echo ${{ github.ref_name }} > ./resources/version

      - name: Compile the PDFs
        env:
          EKN_ROOT_DIR: ${{ github.workspace }}
        run: |
          make notes-all

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 7
          name: notes-${{ github.ref_name }}
          path: |
            build

      - name: Setting up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: scripts/package-lock.json

      - name: Update Website and Google Drive
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_DIR_ID: ${{ secrets.GOOGLE_DIR_ID }}
          DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
          DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
          NOTES_VERSION: ${{ github.ref_name }}
        run: |
          make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
