name: Validate metadata

on:
  push:
  pull_request:

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r metadata/requirements.txt

      - name: Validate metadata
        run: python metadata/scripts/validate_metadata.py
